import { NextFont } from "@next/font";
import "./globals.css";
import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import DoctorProvider from "../../context/doctor";
import UserProvider from "../../context/user";

const poppins: NextFont = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <UserProvider>
          <DoctorProvider>{children}</DoctorProvider>{" "}
        </UserProvider>{" "}
      </body>
    </html>
  );
}
