import { NextFont } from "@next/font";
import "./globals.css";
import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import DoctorProvider from "../../context/doctor";
import UserProvider from "../../context/user";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

const poppins: NextFont = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <DoctorProvider>
          <UserProvider>{children}</UserProvider>{" "}
        </DoctorProvider>{" "}
        <ToastContainer
          position="top-right"
          autoClose={5000}
          hideProgressBar={false}
          newestOnTop={false}
          closeOnClick
          rtl={false}
          pauseOnFocusLoss
          draggable
          pauseOnHover
          theme="light"
        />
        {/* Same as */}
        <ToastContainer />
      </body>
    </html>
  );
}
